 module esmfutils_mod

    use ESMF
    use NUOPC
    use NUOPC_Model, only: NUOPC_ModelGet

contains

    subroutine esmfutils_getImportDataPtr(model, name, ptr, rc)

        implicit none
        type(ESMF_GridComp)  :: model
        character(len=*), intent(in) :: name
        real(8), pointer, intent(out) :: ptr(:, :)
        integer, intent(out) :: rc

        type(ESMF_State)        :: state
        type(ESMF_Field)        :: field
        type(ESMF_Array)        :: array
        integer :: rc2
    
        rc = ESMF_SUCCESS
    
        ! query for importState and exportState
        call NUOPC_ModelGet(model,  importState=state, rc=rc2)
        if (rc2 /= ESMF_SUCCESS) rc = rc + 1

        ! retrieve the field
        call ESMF_StateGet(state, itemName=name, field=field, rc=rc2)
        if (rc2 /= ESMF_SUCCESS) rc = rc + 1

        ! get the array
        call ESMF_FieldGet(field, array=array, rc=rc2)
        if (rc2 /= ESMF_SUCCESS) rc = rc + 1
  
        ! get local pointer to the data. We only have one domain per PE
        call ESMF_ArrayGet(array, localDe=0, farrayPtr=ptr, rc=rc2)
        if (rc2 /= ESMF_SUCCESS) rc = rc + 1
    
    end subroutine esmfutils_getImportDataPtr

    subroutine esmfutils_write2DStructFieldVTK(field, filename)

        type(ESMF_Field) :: field
        character(len=*) :: filename

        integer :: iu, rc, i, j, numPoints, numCells
        type(ESMF_Grid) :: grid
        type(ESMF_StaggerLoc) :: staggerloc
        integer :: minIndex(2), maxIndex(2)
        real(ESMF_KIND_R8), pointer :: xPtr(:), yPtr(:), dataPtr(:, :)
        character(len=128) :: fieldName
        type(ESMF_Array)        :: array

        call ESMF_FieldGet(field, &
         & grid=grid, staggerloc=staggerloc, &
         & minIndex=minIndex, maxIndex=maxIndex, &
         & name=fieldName, &
         & rc=rc)

        call ESMF_GridGetCoord(grid, &
            staggerloc=ESMF_STAGGERLOC_CORNER, &
            coordDim=1, farrayPtr=xPtr)
        call ESMF_GridGetCoord(grid, &
            staggerloc=ESMF_STAGGERLOC_CORNER, &
            coordDim=2, farrayPtr=yPtr)

        numPoints = 1
        numCells = 1
        do i = 1, size(minIndex)
            numPoints = numpoints * (maxIndex(i) - minIndex(i))
            numCells = numCells * (maxIndex(i) - minIndex(i) - 1)
        enddo

        iu = 10
        open(unit=iu, file=filename)
        write(iu, *) '# vtk DataFile Version 3.0'
        write(iu, *) 'File generated by esmfutils'
        write(iu, *) 'ASCII'
        write(iu, *) 'DATASET STRUCTURED_GRID'
        write(iu, '(A, I6, A)') 'POINTS ', numPoints, ' double'
        do j = 1, size(yPtr)
            do i = 1, size(xPtr)
            write(iu, '(2E20.8, A)') &
                 xPtr(i), yPtr(j), ' 0.E0'
            enddo
        enddo

        call ESMF_FieldGet(field, array=array, rc=rc)
        call ESMF_ArrayGet(array, localDe=0, farrayPtr=dataPtr, rc=rc)

        if (staggerloc == ESMF_STAGGERLOC_CENTER) then
            write(iu, '(A, I6)') 'CELL_DATA', numCells
        else
            write(iu, '(A, I6)') 'CELL_DATA', numPoints
        endif
        write(iu, '(A, A, A)') 'SCALARS ', trim(fieldName), ' double 1'
        write(iu, '(A)') 'LOOKUP_TABLE default'
        do j = lbound(dataPtr, 2), ubound(dataPtr, 2)
            do i = lbound(dataPtr, 1), ubound(dataPtr, 1)
                write(iu, '(E20.8)') dataPtr(i, j)
            enddo
        enddo

        close(unit=iu)

    end subroutine esmfutils_write2DStructFieldVTK

 end module esmfutils_mod